# Generated by Django 5.0 on 2023-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CoursesCat')),
                ('categories', models.CharField(max_length=20)),
                ('no_of_courses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='./course-1.jpg', upload_to='UploadedIages')),
                ('number_of_students', models.IntegerField()),
                ('course_duration', models.DurationField()),
                ('instructor', models.CharField(max_length=20)),
            ],
        ),
    ]
